### ISSUE TITLE
Status when reading a file

### ISSUE THREAD

**Issue by john-davies** [craigsapp/midifile#51] opened 2018-03-29 15:38 UTC
When I try to read a file with the `midifile.read()` function ( in MidiFile.cpp ) there are three possible outcomes:

1. File exists and is a valid MIDI file
2. File exists and is not a valid MIDI file
3. File doesn't exist

Cases 1 & 2 work fine but for case 3 the variable `rwstatus` is not set so the subsequent `midifile.status()` call returns the incorrect value. Was this the intention?

I can work round this by checking the return value from the read call rather than explicitly checking the status afterwards.

**Comment by craigsapp** [comment] 2018-04-15 19:40
Somewhat related, I just fixed some problems related to filename handling.  I originally used `string::data()` instead of `string::c_str()` (which is bad) when converting from `char*` for filenames.  Commit https://github.com/craigsapp/midifile/commit/86f935e71c6058da21fbfbc7aa899a58aabdedd0

Using `string::data()` can result in a non-null terminated char* pointers (particular in MacOS).

**Comment by craigsapp** [comment] 2018-04-15 19:56
Commit https://github.com/craigsapp/midifile/commit/c371d75c24374936b0ec3eda9c85f21ac41910aa fixes some problems related to case 1, where the status was being immediately returned, but not stored internally in `MidiFile` class for later access via `MidiFile::status()`.  When starting to read I set `rwstatus` to true, but then I was returning false on failure to find a file but not storing the error, so that `MidiFile::status` was incorrectly returning true when it should have returned false.

**Comment by craigsapp** [comment] 2018-04-15 20:16
In commit https://github.com/craigsapp/midifile/commit/584d95e0f9d9cc2c2e7074edd07fd59d340d41df I improve the error reporting when an ASCII form of MIDI files are read.  This is related to case 2.  case 2 has two subcases: case 2a would be a MIDI file with some syntax error, and case 2b would be a non-MIDI file, either a totally incorrect ASCII version of a MIDI file, or an incorrectly formatted ASCII MIDI file.  When reading an ASCII MIDI file, the parser would continue trying to parse after the first error, but it is better to fail on the first error.

I also added a test program in the same commit called `src-programs/readstatus.cpp` which can be used to test the behavior of the return value of `MidiFile::read()` and the `MidiFile::status()` value.

I have not see a problem with case 2 (2a or 2b) yet, but there was a problem I noticed with case 1 which was fixed in the previous commit.

Here is the result of `bin/readstatus twinkle.mid` when `twinke.mid` is a valid MIDI file:

```
$ bin/readstatus twinkle.mid
Reading from twinkle.mid:	SUCCESS	SUCCESS
```

This is case 1.

The first `SUCCESS` is from the return value of `MidiFile::read()`, the second is from `MidiFile::status()` after reading the MIDI file.

Here is the case when the `twinkle.mid` file does not exists:

```
$ bin/readstatus twinkle.mid
Reading from twinkle.mid:	FAILURE	FAILURE
```

This is case 3, and is not handled correctly (previously the second FAILURE was listed as SUCCESS).

 For case 2a where the file is not a MIDI file and not an ASCII version of a MIDI file:

```
$ bin/readstatus Makefile
Error on line 30 at token: .PHONY
Invalid character in binary number (character is .)
Bad MIDI data input
Reading from Makefile:	FAILURE	FAILURE
```

The first three lines of output are from standard error.  The return status is a FAILURE and the `MidiFile::status()` function also returns FAILURE as expected.

Case 2b, where the file is expected to be a MIDI file, but there is a syntax error.  In this case I delete the "T" from the second byte in the file:

```
$ bin/readstatus twinkle.mid
File twinkle.mid is not a MIDI file
Expecting 'T' at second byte but got 'h'
Reading from twinkle.mid:	FAILURE	FAILURE
```

This is the expected behavior, but there was no fix made for this case.  Perhaps a syntax error at another position in reading of the standard MIDI file is causing a problem for case 2, but I have not noticed where that problem is happening, so potentially your bug report has not yet been fixed.  

I will close the issue for now, but you can reopen it if there is still a problem after all of the above fixes which solve related problems.

**Closed by craigsapp** 2018-04-15 20:16 UTC

**Comment by craigsapp** [comment] 2018-04-15 21:02
I think the problem is related to this function:

```cpp
//////////////////////////////
//
// MidiFile::readByte -- Read one byte from input stream.  Exit if there
//     was an error.
//

uchar MidiFile::readByte(istream& input) {
   uchar buffer[1] = {0};
   input.read((char*)buffer, 1);
   if (input.eof()) {
      cerr << "Error: unexpected end of file." << endl;
      return 0;
   }
   return buffer[0];
}
```

The function originally used to `exit()` if there was a problem.  Now it returns 0 when there is a problem; however, that will cause an error since 0 would be a valid byte to read.

**Comment by craigsapp** [comment] 2018-04-15 21:17
Commit https://github.com/craigsapp/midifile/commit/99bf5e42b726f00d18ad47a6dc88b21172e7852d probably fixes the problem for case 2 (but not extensively tested).

The new code for `MidiFile::readByte` is:

https://github.com/craigsapp/midifile/blob/99bf5e42b726f00d18ad47a6dc88b21172e7852d/src-library/MidiFile.cpp#L2935-L2951
